### ISSUE TITLE
Upgrade to support axum 0.7

### ISSUE THREAD

**Issue by davidBernardWefox** [davidB/tracing-opentelemetry-instrumentation-sdk#115]
- [Announcing axum 0.7.0 | Tokio - An asynchronous Rust runtime](https://tokio.rs/blog/2023-11-27-announcing-axum-0-7-0)
- hyper 1.0,...

Update / provide the compatibility matrix of version: axum - middleware - opentelemetry

**Comment by rakshith-ravi** [comment]
Hey. Just curious - if I were to follow the progress on the upgrade, or help push this forward, what would be the right PR to subscribe to?

**Comment by davidB** [comment]
I started working on it. But I suspend due to
- axum 0.7 removed the simple gracefully shutdown (see its example and the comment related to hyper-utils)
- tonic was not upgraded for hyper 1.0 (being able to support multiple version of hyper in the workspace introduce lot of complexity for just a transition period).

**Comment by davidB** [comment]
IMHO, half fixed but I close the ticket as a version is available for axum-0.7
