### ISSUE TITLE
Change of behavior between 0.18 and 0.19

### ISSUE THREAD

**Issue by nfrankel** [davidB/tracing-opentelemetry-instrumentation-sdk#190]
I've been using your crate for one of my demos, so first, thanks a lot.

The idea is to receive an HTTP request with the `traceparent` HTTP header, start a span, make HTTP calls to other services, and see all of them in Jaeger.

I've noticed a change in behavior between 0.18 and 0.19. With 0.18, I see all spans - the one from the receiving call and the ones from the sending calls. With 0.19, I se nothing. On my side, the code is exactly the same:

```rust
#[tokio::main]
async fn main() {
    // Initialize OTEL
    init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers().unwrap();

    let reqwest_client = Client::builder().build().unwrap();
    let client = ClientBuilder::new(reqwest_client)
        // Insert the tracing middleware
        .with(TracingMiddleware::default())
        .build();

    let app_state = AppState {
        warehouse_env_vars: get_warehouse_env_vars(),
        client,
    };

    // Routing
    let app = axum::Router::new()
        .route("/stocks/:product_id", get(get_stock_by_product_id))
        .with_state(app_state)
        .layer(OtelInResponseLayer::default())
        .layer(OtelAxumLayer::default());

    let listener = TcpListener::bind("0.0.0.0:3000").await.unwrap();

    // Start the server
    axum::serve(listener, app.into_make_service())
        .with_graceful_shutdown(otel::shutdown_signal())
        .await
        .unwrap();
}
```

v0.18 result:

<img width="494" alt="Screenshot 2024-11-29 at 08 15 50" src="https://github.com/user-attachments/assets/2eb90e4f-96ec-484e-ba59-242bee96aff2">

v0.19 (and higher) result:

<img width="968" alt="Screenshot 2024-11-29 at 08 16 58" src="https://github.com/user-attachments/assets/ca652567-6c00-4825-9220-aecd86a541e3">

I've checked the changes between the two versions in the changelog but I didn't see anything related (my Rust skills are pretty low, though).

PS: the project is on [GitHub](https://github.com/nfrankel/opentelemetry-tracing) but it's pretty involved.

**Comment by davidB** [comment]
With 0.19, you should have a warning at compile time, because you should at least manage the output of `init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers().unwrap();`
The output is to keep a reference to the opentelemetry provider, and provide a better handling of shutdown,... it's also due to change in the opentelemetry library.

Has a quickfix you can just change the line to:

```rust
let _guard = init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers().unwrap();
```

Then the `_guard` (and the configured opentelemetry provider) will be dropped at end of the main, and not at end of the call.

**Comment by davidB** [comment]
I just noticed that you used an old version of our crate/library that mismatch the version of opentelemetry that you declare in Cargo.toml, resulting by having 2 versions of opentelemetry (rust is not java, you could have several version of same library). The issue is that opentelemetry use some "static" field (~ one instance per version) => 1/2 opentelemetry is configured.
See [Troubleshot why no trace?](https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/tree/main/init-tracing-opentelemetry#troubleshot-why-no-trace)

For opentelemetry "0.27", use our crates in 0.24 (IIRC)

**Comment by nfrankel** [comment]
Thanks for your feedback @davidB 

Indeed, the issue was because of the duplicate dependencies. When I aligned the version brought by `reqwest_tracing` and the one brought by your lib, everything worked.

Sorry about the bother!
