### ISSUE TITLE
parentbased_always_on by default leading to lost traces

### ISSUE THREAD

**Issue by Jossec101** [davidB/tracing-opentelemetry-instrumentation-sdk#86]
We are missing some traces that don't have a parent span coming from another services instrumented by OTLP, I looked at the code of this and you set `OTEL_TRACES_SAMPLER` by default to `parentbased_always_on`. AFAIK, this means that if no span is parent, it should create a new one and procceed, however, I had to set `OTEL_TRACES_SAMPLER=always_on` to really start seeing all traces. Am I missing something?

We use this lib + otel collector.

**Comment by davidB** [comment]
You are right. On my team, we setup with `always_on` to grab everything because our collector backend is able to record the load 🤞 .
Why it's not the default in the lib, because I follow the specification https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#general-sdk-configuration
